export const userData = [
  {
    type: "CCTV",
    userName: "Usama",
    companyName: "Bytes IT Center",
    date: "23 Nov 2023",
  },
  {
    type: "Firebase",
    userName: "Sami",
    companyName: "Baskan Tech",
    date: "01-09-2023",
  },
  {
    type: "CCTV",
    userName: "Ali",
    companyName: "Soliton Technologies",
    date: "2023-09-08",
  },
  {
    type: "Firebase",
    userName: "Sami",
    companyName: "Baskan Tech",
    date: "01-09-2023",
  },
  {
    type: "Fire System",
    userName: "Sulman",
    companyName: "IT Workshop",
    date: "2023-09-06",
  },
  {
    type: "CCTV",
    userName: "Ali",
    companyName: "Soliton Technologies",
    date: "2023-09-08",
  },
  {
    type: "Firebase",
    userName: "Sami",
    companyName: "Baskan Tech",
    date: "01-09-2023",
  },
  {
    type: "Fire System",
    userName: "Sulman",
    companyName: "IT Workshop",
    date: "2023-09-06",
  },
  {
    type: "CCTV",
    userName: "Ali",
    companyName: "Soliton Technologies",
    date: "2023-09-08",
  },
  {
    type: "CCTV",
    userName: "Ali",
    companyName: "Soliton Technologies",
    date: "2023-09-08",
  },
  {
    type: "Firebase",
    userName: "Sami",
    companyName: "Baskan Tech",
    date: "01-09-2023",
  },
  {
    type: "Fire System",
    userName: "Sulman",
    companyName: "IT Workshop",
    date: "2023-09-06",
  },
  {
    type: "CCTV",
    userName: "Usama",
    companyName: "Bytes IT Center",
    date: "23 Nov 2023",
  },
  {
    type: "Firebase",
    userName: "Sami",
    companyName: "Baskan Tech",
    date: "01-09-2023",
  },
  {
    type: "Fire System",
    userName: "Sulman",
    companyName: "IT Workshop",
    date: "2023-09-06",
  },
  {
    type: "CCTV",
    userName: "Usama",
    companyName: "Bytes IT Center",
    date: "23 Nov 2023",
  },
  {
    type: "Firebase",
    userName: "Sami",
    companyName: "Baskan Tech",
    date: "01-09-2023",
  },
  {
    type: "CCTV",
    userName: "Ali",
    companyName: "Soliton Technologies",
    date: "2023-09-08",
  },
  {
    type: "Firebase",
    userName: "Sami",
    companyName: "Baskan Tech",
    date: "01-09-2023",
  },
  {
    type: "Fire System",
    userName: "Sulman",
    companyName: "IT Workshop",
    date: "2023-09-06",
  },
  {
    type: "CCTV",
    userName: "Ali",
    companyName: "Soliton Technologies",
    date: "2023-09-08",
  },
  {
    type: "Firebase",
    userName: "Sami",
    companyName: "Baskan Tech",
    date: "01-09-2023",
  },
  {
    type: "Fire System",
    userName: "Sulman",
    companyName: "IT Workshop",
    date: "2023-09-06",
  },
  {
    type: "CCTV",
    userName: "Ali",
    companyName: "Soliton Technologies",
    date: "2023-09-08",
  },
  {
    type: "CCTV",
    userName: "Ali",
    companyName: "Soliton Technologies",
    date: "2023-09-08",
  },
  {
    type: "Firebase",
    userName: "Sami",
    companyName: "Baskan Tech",
    date: "01-09-2023",
  },
  {
    type: "Fire System",
    userName: "Sulman",
    companyName: "IT Workshop",
    date: "2023-09-06",
  },
  {
    type: "CCTV",
    userName: "Usama",
    companyName: "Bytes IT Center",
    date: "23 Nov 2023",
  },
  {
    type: "Firebase",
    userName: "Sami",
    companyName: "Baskan Tech",
    date: "01-09-2023",
  },
  {
    type: "Fire System",
    userName: "Sulman",
    companyName: "IT Workshop",
    date: "2023-09-06",
  },
  // Add more data as needed
];
